# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/cmake-lint/cmake-lint
    rev: 1.4.2
    hooks:
      - id: cmakelint
        args: ["--linelength=100"]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.3
    hooks:
      - id: clang-format
        exclude_types: [json]
  - repo: https://github.com/f-koehler/qml-pre-commit
    rev: v0.2.0
    hooks:
      - id: qmlformat
      - id: qmllint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier
